### ISSUE TITLE
TypeError Popup when run on android

### ISSUE THREAD

**Issue by tomyamGTX** [Bandito11/Game-is-active-plugin#1]
Cannot read properties of undefined (reading'undefined')

**Comment by Bandito11** [comment]
I am checking it out.

edit: 
was able to replicate the issue. Currently fixing it.

**Comment by Bandito11** [comment]
Ok, I am still having issue on iOS, but I find that this plugin is not needed for Android. When you disable it, does the game loads when the app starts?

When you run the build on Android Studio, or deploy on your device, does the game load automatically? It does on my phone and I tested on Android Studio.

I am having issues with iOS though, and the game doesn't load automatically on that platform. Still try to find the issue.

**Comment by tomyamGTX** [comment]
> Ok, I am still having issue on iOS, but I find that this plugin is not needed for Android. When you disable it, does the game loads when the app starts?
> 
> When you run the build on Android Studio, or deploy on your device, does the game load automatically? It does on my phone and I tested on Android Studio.
> 
> I am having issues with iOS though, and the game doesn't load automatically on that platform. Still try to find the issue.

When I disable it, The game not initialize onload. but after click black area, the title appear. I find the solution by modifying rmmz_managers.js. but every deploy need to adjust it

SceneManager.isGameActive = function() {
   return true;
};

**Comment by Bandito11** [comment]
Verify the plugin now. Instead of declaring a `prototype` I just assigned a new value to the `isGameActive` method again (just as it is done on the `rmmz_managers.js`). A value is only assigned for when the browser runs on an iPhone, iPad or Android. It was tested to run on the iPhone and iPad xCode emulators, but I haven't tested on real devices. It runs on Android too, but as explained before, I never needed to use the plugin on my Android device.

**Comment by tomyamGTX** [comment]
Cool. The plugin working properly right now. I use Webview for my Android app actually. I just figure it out after applying the same game in the Flutter app.
